# Generated by Django 4.2 on 2023-04-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'profesional', 'verbose_name_plural': 'profesionales'},
        ),
    ]
